In [9]:
#Input
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])


In [10]:
#Task 1 Print the shape of data. Then compute and print the mean temperature per station (one value per row).
print(f"Shape of data = {data.shape}")
print(f"Mean temperature per station = {np.mean(data,axis=1)}")

Shape of data = (4, 5)
Mean temperature per station = [25.3  23.78 26.58 25.26]


In [12]:
#Task 2 Using a boolean mask, extract all temperature readings above 28.0°C and print them as a 1D array.
mask = data > 28.0
if np.any(mask):
  print(f"Temperature readings above 28.0°C : {data[mask]}")


Temperature readings above 28.0°C : [31.2 28.7 30.5 33.1 29.6 31.9 28.1]


In [17]:
#Task 3 Normalize the entire data array to the range [0, 1] using the formula below and print the result rounded to 2 decimal places:
#normalized = (data - data.min()) / (data.max() - data.min())

normalized = (data - data.min()) / (data.max() - data.min())
print(f"Normalized Data: \n\n {np.round(normalized,2)}")

Normalized Data: 

 [[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
